-- Operator Watch: Supabase setup (generated by server/operator-watch/scripts/build-supabase-setup.mjs — do not edit).
--
-- Run in Supabase → SQL editor, in the site's project. Safe to run again.
-- Before running, replace the two placeholders below:
--   CHANGE_ME_DB_PASSWORD  a new strong password for the operator_watch database role (goes into DATABASE_URL)
--   CHANGE_ME_SITE_URL     the site's production URL, e.g. https://seatos-commercial.vercel.app (no trailing slash)
-- and store the cron secret in Vault (step 4) with the same value as the CRON_SECRET env var on Vercel.

-- 1. A login role that owns a private schema. The API connects as this role, so it can only see its own tables
--    (plus read access to public.allowed_users). The schema is not exposed through the Supabase REST API.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'operator_watch') then
    create role operator_watch login password 'CHANGE_ME_DB_PASSWORD';
  end if;
end
$$;
grant operator_watch to postgres;
create schema if not exists operator_watch authorization operator_watch;
alter role operator_watch set search_path = operator_watch;
grant usage on schema public to operator_watch;
grant select on public.allowed_users to operator_watch;

-- 2. Tables, created as operator_watch so it owns them.
set role operator_watch;
set search_path = operator_watch;
create table if not exists operator_watch.schema_migrations (name text primary key, applied_at timestamptz not null default now());

do $ow$
begin
  if not exists (select 1 from operator_watch.schema_migrations where name = '001_workspace.sql') then
    execute $ow_migration$
-- Commercial Workspace: Operator Watch runs, cases, drafts, approvals and sending.
-- Applied by src/infrastructure/database/migrator.ts (tracked in schema_migrations).

-- Admin-only configuration (pipeline cadence, agent, sending, guards). Secrets never live here.
create table app_settings (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now(),
  updated_by  text
);

-- Immutable CRM pull. Every run reasons over exactly one snapshot.
create table crm_snapshots (
  id             uuid primary key,
  source         text not null check (source in ('mock', 'hubspot')),
  portal         text not null,
  description    text not null,
  pulled_at      timestamptz not null,
  content_hash   text not null,
  account_count  integer not null,
  accounts       jsonb not null,
  created_at     timestamptz not null default now()
);

-- One pipeline execution. period_key makes scheduled runs idempotent across instances.
create table workflow_runs (
  id                uuid primary key,
  kind              text not null default 'operator_watch',
  period_key        text not null,
  label             text not null,
  trigger           text not null check (trigger in ('schedule', 'manual')),
  status            text not null check (status in ('running', 'completed', 'failed')),
  agent             text not null,
  playbook_version  text,
  snapshot_id       uuid not null references crm_snapshots(id),
  case_seq          integer not null default 0,
  summary           text,
  error             text,
  triggered_by      text,
  started_at        timestamptz not null default now(),
  completed_at      timestamptz,
  unique (kind, period_key)
);
create index workflow_runs_started_idx on workflow_runs (started_at desc);

-- One operator's work within one run. The agent submits it; people decide on it.
create table operator_cases (
  id                uuid primary key,
  run_id            uuid not null references workflow_runs(id),
  case_ref          text not null,
  operator_id       text not null,
  operator_name     text not null,
  owner             text,
  segment           text not null,
  health            text not null,
  crm_health        text not null,
  outcome           text not null check (outcome in ('outreach', 'no_action')),
  state             text not null check (state in ('pending', 'approved', 'hold', 'rejected', 'closed', 'expired', 'no_action', 'reactive')),
  playbook          text not null,
  play_type         text not null,
  signals           jsonb not null default '[]',
  analysis          text not null default '',
  next_step         text not null default '',
  language          text not null default 'en',
  author            text not null,
  playbook_version  text,
  current_draft_id  uuid,
  reject_reason     text,
  void_note         text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (run_id, operator_id),
  unique (case_ref)
);
create index operator_cases_operator_idx on operator_cases (operator_id, created_at desc);
create index operator_cases_open_idx on operator_cases (state) where state in ('pending', 'hold');

-- Draft versions are never edited in place; approvals bind to draft_hash.
create table case_drafts (
  id          uuid primary key,
  case_id     uuid not null references operator_cases(id),
  version     integer not null,
  language    text not null,
  subject     text not null,
  body        text not null,
  draft_hash  text not null,
  author      text not null,
  writer      text not null check (writer in ('agent', 'template', 'human')),
  mods        jsonb not null default '{}',
  qa          text not null default 'not_run',
  created_at  timestamptz not null default now(),
  unique (case_id, version)
);
alter table operator_cases add constraint operator_cases_current_draft_fk foreign key (current_draft_id) references case_drafts(id);

create table case_decisions (
  id          uuid primary key,
  case_id     uuid not null references operator_cases(id),
  draft_id    uuid references case_drafts(id),
  decision    text not null check (decision in ('approve', 'hold', 'reject', 'close', 'reopen')),
  reason      text,
  channel     text,
  recipient   text,
  actor_id    text not null,
  actor_name  text not null,
  created_at  timestamptz not null default now()
);

-- Timeline shown on the account record (per operator, across runs).
create table case_events (
  id           uuid primary key,
  operator_id  text not null,
  case_id      uuid references operator_cases(id),
  at           text not null,
  kind         text not null,
  origin       text not null,
  text         text not null,
  note         text,
  crm_sync     text,
  crm_error    text,
  created_at   timestamptz not null default now()
);
create index case_events_operator_idx on case_events (operator_id, created_at);
create index case_events_user_idx on case_events (created_at desc) where origin = 'user';

-- The exact approved text is copied here; the sender never re-renders or calls a model.
create table send_jobs (
  id                   uuid primary key,
  case_id              uuid not null references operator_cases(id),
  draft_id             uuid not null references case_drafts(id),
  draft_hash           text not null,
  channel              text not null check (channel in ('smtp', 'hubspot')),
  recipient            text not null,
  subject              text not null,
  body                 text not null,
  token                text not null,
  status               text not null check (status in ('queued', 'sending', 'sent', 'failed', 'cancelled')),
  delivered_to         text,
  scheduled_for        timestamptz not null,
  attempts             integer not null default 0,
  provider_message_id  text,
  error                text,
  sent_at              timestamptz,
  created_at           timestamptz not null default now()
);
create index send_jobs_due_idx on send_jobs (scheduled_for) where status = 'queued';
create index send_jobs_case_idx on send_jobs (case_id);
$ow_migration$;
    insert into operator_watch.schema_migrations (name) values ('001_workspace.sql');
    raise notice 'Applied 001_workspace.sql';
  end if;
end
$ow$;

do $ow$
begin
  if not exists (select 1 from operator_watch.schema_migrations where name = '002_chat.sql') then
    execute $ow_migration$
-- Group chat about one operator: every team member's questions and the agent's answers, in one shared thread.
create table chat_messages (
  id           uuid primary key,
  operator_id  text not null,
  role         text not null check (role in ('user', 'assistant')),
  author_id    text not null,
  author_name  text not null,
  text         text not null,
  created_at   timestamptz not null default now()
);
create index chat_messages_operator_idx on chat_messages (operator_id, created_at, id);
$ow_migration$;
    insert into operator_watch.schema_migrations (name) values ('002_chat.sql');
    raise notice 'Applied 002_chat.sql';
  end if;
end
$ow$;

do $ow$
begin
  if not exists (select 1 from operator_watch.schema_migrations where name = '003_auth.sql') then
    execute $ow_migration$
-- Authentication & authorization: users (one role each), operator memberships, audit trail.

create table auth_users (
  id            text primary key,
  -- Google's immutable account identifier; never reused for another person.
  subject       text not null unique,
  email         text not null,
  role          text not null check (role in ('admin', 'analyst', 'viewer')),
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_login_at timestamptz
);

create unique index auth_users_email_key on auth_users (lower(email));
create index auth_users_role_idx on auth_users (role) where active;

-- Operator-scoped permissions (e.g. dashboard:read) require a membership unless the role spans all operators.
create table auth_operator_memberships (
  user_id     text not null references auth_users (id) on delete cascade,
  operator_id text not null,
  created_at  timestamptz not null default now(),
  primary key (user_id, operator_id)
);

-- Append-only. No foreign key on purpose: the trail must outlive any user row.
create table auth_audit_events (
  id          bigserial primary key,
  user_id     text not null,
  action      text not null,
  operator_id text,
  detail      jsonb,
  at          timestamptz not null default now()
);

create index auth_audit_events_user_idx on auth_audit_events (user_id, at desc);
create index auth_audit_events_action_idx on auth_audit_events (action, at desc);
$ow_migration$;
    insert into operator_watch.schema_migrations (name) values ('003_auth.sql');
    raise notice 'Applied 003_auth.sql';
  end if;
end
$ow$;

do $ow$
begin
  if not exists (select 1 from operator_watch.schema_migrations where name = '004_send_job_delivery.sql') then
    execute $ow_migration$
-- Delivery bookkeeping for the send queue.
--   claimed_at        lease start: a job stuck in 'sending' past the lease is marked failed ("delivery uncertain")
--                     instead of being resent, because SMTP has no idempotency.
--   provider_response the provider's acceptance line (SMTP reply / HubSpot status) for the audit trail.
alter table send_jobs add column claimed_at timestamptz;
alter table send_jobs add column provider_response text;
create index send_jobs_sending_idx on send_jobs (claimed_at) where status = 'sending';
$ow_migration$;
    insert into operator_watch.schema_migrations (name) values ('004_send_job_delivery.sql');
    raise notice 'Applied 004_send_job_delivery.sql';
  end if;
end
$ow$;

do $ow$
begin
  if not exists (select 1 from operator_watch.schema_migrations where name = '005_operator_links.sql') then
    execute $ow_migration$
-- Which SeatOS (TMS) operator a workspace account is, resolved once so agents never look it up by name.
--   status 'needs_confirmation': several or inexact matches, `candidates` holds up to 10 for a person to pick from.
--   source 'human' links are never re-resolved automatically.
create table operator_links (
  account_id        text primary key,
  status            text not null check (status in ('linked', 'needs_confirmation', 'not_found')),
  tms_operator_id   integer,
  tms_operator_name text,
  source            text check (source in ('lookup', 'human')),
  candidates        jsonb not null default '[]',
  resolved_at       timestamptz not null,
  confirmed_by      text
);
$ow_migration$;
    insert into operator_watch.schema_migrations (name) values ('005_operator_links.sql');
    raise notice 'Applied 005_operator_links.sql';
  end if;
end
$ow$;

do $ow$
begin
  if not exists (select 1 from operator_watch.schema_migrations where name = '006_claude_agent.sql') then
    execute $ow_migration$
-- Claude agent (runs inside the API, no separate agent server): a work queue for run assessments and the agent's
-- long-term memory. Applied by src/infrastructure/database/migrator.ts or supabase/setup.sql.

-- One job per operator in a run. The scheduler tick claims a few at a time under a lease, so overlapping ticks never
-- assess the same operator twice; a job whose lease expired (the function was stopped) is picked up again.
create table agent_jobs (
  id               uuid primary key,
  run_id           uuid not null references workflow_runs(id) on delete cascade,
  operator_id      text not null,
  operator_name    text not null,
  tms_operator_id  integer,
  status           text not null default 'pending' check (status in ('pending', 'working', 'done', 'failed')),
  attempts         integer not null default 0,
  lease_until      timestamptz,
  error            text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (run_id, operator_id)
);
create index agent_jobs_due on agent_jobs (status, lease_until);

-- What the agent remembers: facts about one operator, or team-wide lessons (operator_id null). Written only by the
-- backend from what happened (chats, assessments, decisions, sends), never by the model directly. A fact that a newer
-- one replaces keeps its row with superseded_by set.
create table agent_memories (
  id             uuid primary key,
  operator_id    text,
  kind           text not null check (kind in ('chat', 'case', 'decision', 'email')),
  text           text not null,
  topics         text[] not null default '{}',
  source         text,
  superseded_by  uuid references agent_memories(id),
  created_at     timestamptz not null default now(),
  search         tsvector generated always as (to_tsvector('simple', text)) stored
);
create index agent_memories_operator on agent_memories (operator_id, created_at desc) where superseded_by is null;
create index agent_memories_search on agent_memories using gin (search);
$ow_migration$;
    insert into operator_watch.schema_migrations (name) values ('006_claude_agent.sql');
    raise notice 'Applied 006_claude_agent.sql';
  end if;
end
$ow$;

do $ow$
begin
  if not exists (select 1 from operator_watch.schema_migrations where name = '007_weekly_data.sql') then
    execute $ow_migration$
-- Weekly SeatOS numbers uploaded by the team (CSV exports from Looker), one row per operator per week:
-- feature usage (WAO) and tickets/GMV. Re-uploading a week replaces that week's rows for that file.
-- name_key is the normalised operator name used for matching; account_id is the matched workspace account (HubSpot
-- main deal), or null when the name did not match.

create table weekly_usage (
  week                     date not null,
  operator_name            text not null,
  name_key                 text not null,
  account_id               text,
  inventory_management     boolean not null,
  distribution_management  boolean not null,
  reservation_management   boolean not null,
  trip_management          boolean not null,
  fleet_management         boolean not null,
  analytics                boolean not null,
  accounting               boolean not null,
  feature_count            integer not null,
  uploaded_at              timestamptz not null default now(),
  uploaded_by              text not null,
  primary key (week, operator_name)
);
create index weekly_usage_account on weekly_usage (account_id, week desc);
create index weekly_usage_name on weekly_usage (name_key);

create table weekly_tickets (
  week           date not null,
  operator_name  text not null,
  name_key       text not null,
  account_id     text,
  gmv_usd        numeric(14, 2) not null,
  tickets        integer not null,
  uploaded_at    timestamptz not null default now(),
  uploaded_by    text not null,
  primary key (week, operator_name)
);
create index weekly_tickets_account on weekly_tickets (account_id, week desc);
create index weekly_tickets_name on weekly_tickets (name_key);

-- Names in the uploads that a person matched to an account by hand (normalised name → account), reused every week.
-- account_id null = "not an operator we track" (e.g. a demo account): never reported as unmatched again.
create table operator_name_links (
  name_key    text primary key,
  account_id  text,
  set_by      text not null,
  set_at      timestamptz not null default now()
);
$ow_migration$;
    insert into operator_watch.schema_migrations (name) values ('007_weekly_data.sql');
    raise notice 'Applied 007_weekly_data.sql';
  end if;
end
$ow$;

reset role;
reset search_path;

-- 3. Scheduler: call the API's tick every minute (opens due runs, sends due emails).
create extension if not exists pg_cron;
create extension if not exists pg_net;

-- 4. The cron secret, kept in Vault rather than in the job text. Run once with your value (same as CRON_SECRET on Vercel):
--      select vault.create_secret('<the CRON_SECRET value>', 'operator_watch_cron_secret');
--    To change it later: select vault.update_secret((select id from vault.secrets where name = 'operator_watch_cron_secret'), '<new value>');

select cron.unschedule(jobid) from cron.job where jobname = 'operator-watch-tick';
select cron.schedule(
  'operator-watch-tick',
  '* * * * *',
  $cron$
  select net.http_post(
    url := 'CHANGE_ME_SITE_URL/api/ow/internal/tick',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'operator_watch_cron_secret')
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 55000
  );
  $cron$
);
