/**
 * The team's CS Toolkit (Playbook → CS Toolkit), given to Claude so its advice follows how SeatOS does Customer Success.
 * A copy of the arrays in src/playbook/sections/CSToolkit.jsx: edit both together (CSToolkit.sync.test.ts fails
 * when they differ).
 */
export interface CsTip {
  readonly n: string;
  readonly cat: 'adoption' | 'people' | 'risk' | 'run';
  readonly title: string;
  readonly body: string;
  readonly bullets: readonly string[];
  readonly tip: string;
}

export const CS_GOLDEN_RULES: readonly string[] = [
  'Be proactive, not reactive.',
  'Understand the business before the system.',
  'Adoption is the goal, not go-live.',
  'One champion is never enough.',
  'Every meeting needs a next step.',
  'Small issues become churn if ignored.',
  'Solve business problems, not just support tickets.',
  'Create value before asking for renewal.',
  'Every customer should achieve a quick win.',
  'Help operators grow — that’s what Customer Success means at seatOS.',
];

export const CS_TIPS: readonly CsTip[] = [
  {
    n: '1',
    cat: 'adoption',
    title: 'Understand the customer before the system',
    body: 'Before giving advice, understand how the operator actually works.',
    bullets: [
      'How do they sell tickets today?',
      'Which channels do they use?',
      'Which tasks are still manual?',
      'Which team uses seatOS daily?',
      'Which process causes the most complaints?',
      'Which reports does management care about?',
      'What did they expect when they signed?',
    ],
    tip: 'Don’t assume the customer needs more training — the real issue is often workflow, ownership, management direction or internal discipline.',
  },
  {
    n: '2',
    cat: 'adoption',
    title: 'Adoption is more important than go-live',
    body: 'Go-live is only the beginning. A customer is successful when seatOS becomes part of their daily operation.',
    bullets: [
      'Are users logging in?',
      'Are bookings being created?',
      'Are trips managed in seatOS?',
      'Are reports being used?',
      'Are manual processes reduced?',
      'Are problems still handled outside the system?',
    ],
    tip: 'If they go live but still work mainly in Excel, WhatsApp or manual reports, adoption is not complete.',
  },
  {
    n: '3',
    cat: 'adoption',
    title: 'Focus on daily habits',
    body: 'Customers adopt seatOS when it becomes their normal way of working. Train on what users do every day, not every feature.',
    bullets: [
      'Counter staff: create bookings quickly',
      'Operations: manage trips & passenger manifests',
      'Management: read reports',
      'Finance: invoices, sales & reconciliation',
      'Customer service: changes & passenger updates',
    ],
    tip: 'Don’t teach everything at once — teach the workflow that helps them tomorrow morning.',
  },
  {
    n: '4',
    cat: 'adoption',
    title: 'Create a quick win early',
    body: 'Every customer should experience one visible success within the first week after go-live.',
    bullets: [
      'First booking created',
      'First OTA booking received correctly',
      'First passenger manifest exported',
      'First successful check-in',
      'First report reviewed by management',
      'First issue resolved faster than before',
    ],
    tip: 'A quick win builds confidence. Confidence builds adoption.',
  },
  {
    n: '5',
    cat: 'risk',
    title: 'Don’t ask only “any problem?”',
    body: 'Customers say “no problem” even when adoption is weak. Ask better questions.',
    bullets: [
      'Which part of your work still takes too much time?',
      'Which task are you still doing outside seatOS?',
      'Which team uses seatOS the least?',
      'Which report do you still prepare manually?',
      'What do your staff complain about most?',
      'What is still confusing for your team?',
    ],
    tip: 'Good CS questions reveal hidden risk before the customer complains.',
  },
  {
    n: '6',
    cat: 'risk',
    title: 'Silence is a risk signal',
    body: 'A quiet customer is not always a happy customer. They may be:',
    bullets: [
      'Not using the system',
      'Confused or losing confidence',
      'Using another process',
      'Waiting for renewal to cancel',
      'Depending on one person internally',
      'Not seeing value',
    ],
    tip: 'If a customer stops replying, stops joining meetings or stops logging in, treat it as a risk.',
  },
  {
    n: '7',
    cat: 'people',
    title: 'Build more than one relationship',
    body: 'Never depend on only one champion — if your contact leaves or loses influence, the account becomes risky.',
    bullets: [
      'Daily users',
      'Operations manager',
      'Finance contact',
      'Commercial contact',
      'Owner / management',
      'IT or system admin',
    ],
    tip: 'A healthy account has multiple contacts who understand why seatOS matters.',
  },
  {
    n: '8',
    cat: 'people',
    title: 'Match the message to the stakeholder',
    body: 'Different people care about different value.',
    bullets: [
      'Operations: faster work, fewer mistakes, clear workflow',
      'Finance: reports, payment tracking, reconciliation, control',
      'Commercial: more channels, more bookings, inventory',
      'Management: growth, visibility, standardization, scalability',
    ],
    tip: 'Don’t explain seatOS the same way to everyone.',
  },
  {
    n: '9',
    cat: 'people',
    title: 'Every meeting needs a clear next step',
    body: 'A meeting without a next step is not complete. Before ending, confirm:',
    bullets: [
      'What was agreed?',
      'Who owns the action?',
      'When will it be done?',
      'What happens next?',
      'When is the next meeting?',
    ],
    tip: 'Always summarize next steps before leaving the call.',
  },
  {
    n: '10',
    cat: 'people',
    title: 'Follow up within 24 hours',
    body: 'After every important meeting, send a short recap.',
    bullets: [
      'What was discussed',
      'What was agreed',
      'Open issues',
      'Owner of each action',
      'Next meeting date',
    ],
    tip: 'Fast follow-up creates trust and keeps momentum.',
  },
  {
    n: '11',
    cat: 'people',
    title: 'Own the problem even if another team fixes it',
    body: 'CS may not solve every technical issue, but CS owns customer communication.',
    bullets: [
      'Acknowledge it',
      'Explain what is being checked',
      'Give an expected update time',
      'Follow up even with no final answer',
      'Close the loop when resolved',
    ],
    tip: 'Customers can accept problems — they lose trust when communication is unclear.',
  },
  {
    n: '12',
    cat: 'risk',
    title: 'Escalate early',
    body: 'Don’t wait until the customer is angry. Escalate when:',
    bullets: [
      'The customer is not using the system',
      'A critical issue repeats',
      'A promised feature is delayed',
      'A decision maker is unhappy',
      'The customer mentions cancellation',
      'Internal ownership is unclear',
    ],
    tip: 'Early escalation prevents churn.',
  },
  {
    n: '13',
    cat: 'adoption',
    title: 'Don’t over-train',
    body: 'More training isn’t always the answer. If a customer isn’t adopting, check the real cause.',
    bullets: [
      'Is the workflow too complicated?',
      'Did management enforce the process?',
      'Are users avoiding change?',
      'Is the wrong person trained?',
      'Is the feature relevant to their work?',
      'Are they still using the old process?',
    ],
    tip: 'Training teaches knowledge. Adoption changes behavior.',
  },
  {
    n: '14',
    cat: 'adoption',
    title: 'Connect every feature to a business outcome',
    body: 'Don’t say “please use this feature.” Say why it matters.',
    bullets: [
      '“This reduces manual work for your team.”',
      '“This lets management see route performance.”',
      '“This helps avoid missed bookings.”',
      '“This helps your counter team sell faster.”',
    ],
    tip: 'Customers adopt features faster when they understand why the feature matters.',
  },
  {
    n: '15',
    cat: 'adoption',
    title: 'Identify manual work',
    body: 'Manual work is usually where value is hiding.',
    bullets: [
      'Excel tracking',
      'WhatsApp coordination',
      'Manual OTA updates',
      'Manual passenger lists',
      'Manual invoice checking',
      'Manual report preparation',
      'Manual refund tracking',
    ],
    tip: 'Every manual process is a potential adoption opportunity.',
  },
  {
    n: '16',
    cat: 'risk',
    title: 'Turn complaints into adoption opportunities',
    body: 'When customers complain, don’t only solve the complaint — find the root.',
    bullets: [
      'Why is this happening?',
      'One-time issue or repeated process?',
      'Which team is affected?',
      'Is there a seatOS workflow that prevents this?',
      'Do we need to retrain the team?',
    ],
    tip: 'A complaint often shows where the customer hasn’t fully adopted the system.',
  },
  {
    n: '17',
    cat: 'risk',
    title: 'Review health every week',
    body: 'Customer health shouldn’t be based only on feeling.',
    bullets: [
      'Login activity',
      'Booking activity',
      'Feature usage',
      'Support tickets & open issues',
      'Payment status',
      'Management engagement',
      'Renewal timeline',
    ],
    tip: 'A customer can be friendly but still unhealthy.',
  },
  {
    n: '18',
    cat: 'risk',
    title: 'Watch for churn signals',
    body: 'Churn rarely happens suddenly — the signs appear weeks or months earlier.',
    bullets: [
      'Low login or booking activity',
      'No response',
      'Repeated complaints',
      'Management change',
      'New competitor/system mentioned',
      'Payment delay',
      'Low meeting attendance',
      'They stop asking questions',
    ],
    tip: 'Spot the signals early and act before renewal.',
  },
  {
    n: '19',
    cat: 'run',
    title: 'Prepare before every customer meeting',
    body: 'Before meeting the customer, check the account.',
    bullets: [
      'Latest usage',
      'Open tickets',
      'Previous meeting notes',
      'Commercial package & renewal date',
      'Key stakeholders',
      'Pending actions',
      'Health status',
    ],
    tip: 'Customers can feel when CS is prepared — preparation builds credibility.',
  },
  {
    n: '20',
    cat: 'run',
    title: 'Don’t let issues stay vague',
    body: 'Avoid vague notes like “customer has issue with report.”',
    bullets: [
      'Who is affected — team & branch?',
      'What exactly is wrong?',
      'Who owns the next action, and by when?',
    ],
    tip: 'Write it clearly, e.g. “Finance can’t match daily sales with counter payments for Phuket branch — collect sample by Friday, product to review logic by Tuesday.”',
  },
  {
    n: '21',
    cat: 'run',
    title: 'Help customers standardize',
    body: 'seatOS creates more value when customers use one standard process across teams and branches.',
    bullets: [
      'Do all branches follow the same process?',
      'Are teams using different spreadsheets?',
      'Does management get consistent reports?',
      'Are user roles clearly defined?',
    ],
    tip: 'Standardization is one of the strongest values seatOS delivers to larger operators.',
  },
  {
    n: '22',
    cat: 'run',
    title: 'Renewal starts on day one',
    body: 'Don’t wait until the contract is nearly over. Renewal depends on:',
    bullets: [
      'Adoption',
      'Trust',
      'Business value',
      'Issue resolution',
      'Management engagement',
      'A clear success story',
    ],
    tip: 'If the customer can’t explain the value of seatOS before renewal, the renewal is at risk.',
  },
  {
    n: '23',
    cat: 'run',
    title: 'Expansion comes from pain, not selling',
    body: 'Don’t push another product too early — look for the signal.',
    bullets: [
      'Too many passenger questions → Notify',
      'Long counter queues → POS or Kiosk',
      'Many manual OTA updates → Channel Manager',
      'Drivers need trip details → Driver App',
      'Management wants visibility → Dashboard',
      'Many agents → Agency Management',
    ],
    tip: 'Never sell another module — solve the next business problem.',
  },
  {
    n: '24',
    cat: 'run',
    title: 'Record everything in HubSpot',
    body: 'If it’s not in HubSpot, the team can’t manage it properly.',
    bullets: [
      'Meeting notes & customer goals',
      'Risks & open issues',
      'Next actions',
      'Stakeholders',
      'Feature requests',
      'Expansion opportunities',
      'Renewal risks',
    ],
    tip: 'Good HubSpot hygiene protects the customer and the company.',
  },
  {
    n: '25',
    cat: 'run',
    title: 'Be proactive, not reactive',
    body: 'Don’t wait for the customer to contact you.',
    bullets: [
      'Check usage before problems happen',
      'Follow up after go-live',
      'Review customer health',
      'Suggest better workflows',
      'Identify risks early',
      'Help customers prepare for peak season',
    ],
    tip: 'Good support solves today’s problem. Great Customer Success prevents tomorrow’s.',
  },
  {
    n: '26',
    cat: 'run',
    title: 'Keep the customer focused',
    body: 'Customers may request many things — help them prioritize.',
    bullets: [
      'What is blocking go-live?',
      'What affects daily operation?',
      'What affects revenue?',
      'What affects passengers?',
      'What can wait?',
    ],
    tip: 'Not every request has the same priority — help customers focus on what matters most.',
  },
  {
    n: '27',
    cat: 'run',
    title: 'Be careful with promises',
    body: 'Don’t promise custom features, timelines, integrations or commercial terms without internal confirmation.',
    bullets: [
      '“Let me confirm with the relevant team and come back with a clear answer.”',
    ],
    tip: 'Trust is built by being reliable, not by saying yes to everything.',
  },
  {
    n: '28',
    cat: 'run',
    title: 'Close the loop',
    body: 'Never leave the customer wondering. When something is done:',
    bullets: [
      'Tell the customer',
      'Explain what changed',
      'Ask them to test',
      'Confirm if it is resolved',
      'Update HubSpot',
    ],
    tip: 'An issue isn’t closed until the customer confirms or the resolution is clearly communicated.',
  },
  {
    n: '29',
    cat: 'people',
    title: 'Create customer confidence',
    body: 'Customers should feel that CS:',
    bullets: [
      'Understands their business',
      'Is responsive',
      'Is organized',
      'Follows up',
      'Cares about their success',
    ],
    tip: 'Confidence is created through small, consistent actions.',
  },
  {
    n: '30',
    cat: 'run',
    title: 'Remember the seatOS mission',
    body: 'seatOS helps ground and sea transport operators:',
    bullets: [
      'Connect every sales channel',
      'Reduce manual work',
      'Improve visibility',
      'Standardize operations',
      'Grow without unnecessary complexity',
    ],
    tip: 'Every CS action should help the customer move closer to that outcome.',
  },
];

/** The toolkit as a compact prompt block: the rules, then each tip as one line with its checklist. */
export function formatCsToolkit(): string {
  const rules = CS_GOLDEN_RULES.map((r, i) => `${i + 1}. ${r}`).join('\n');
  const tips = CS_TIPS.map((t) => `Tip ${t.n} — ${t.title}: ${t.body} (${t.bullets.join('; ')}) → ${t.tip}`).join('\n');
  return `Golden rules\n${rules}\n\nThe 30 CS tips\n${tips}`;
}
